name: 'Setup Environment'
description: 'Installs Rust and Dependencies'
inputs:
  target-os:
    required: true
    description: "Target to run action on (usually ubuntu-latest or macos-latest)"
runs:
  using: 'composite'
  runs-on: ${{ inputs.target-os }}
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install Rust 
      uses: dtolnay/rust-toolchain@stable
    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Install plotters dependencies
      shell: bash
      run: sudo apt install pkg-config libfreetype6-dev libfontconfig1-dev

