name: 'Setup Environment'
description: 'Installs Rust and Dependencies'
runs:
  using: 'composite'
  shell: bash
  steps:
    - name: Install Rust 
      uses: dtolnay/rust-toolchain@stable
    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2

