//! This module contains the parser for programs in the surface language Fun.
use lalrpop_util::lalrpop_mod;
use result::ParseError;

use crate::syntax::{program::Program, terms::Term};

pub mod result;
pub mod util;

lalrpop_mod!(
    #[allow(clippy::all)]
    #[allow(unused_imports)]
    #[allow(dead_code)]
    /// This module contains the parser generated by `lalrpop`.
    pub fun, "/parser/fun.rs"
);

/// This function parses a term from a string.
pub fn parse_term(s: &str) -> Result<Term, ParseError> {
    let parser = fun::TermParser::new();
    parser.parse(s).map_err(From::from)
}

/// This function parses a module from a string.
pub fn parse_module(s: &str) -> Result<Program, ParseError> {
    let parser = fun::ProgParser::new();
    parser.parse(s).map_err(From::from)
}

/// This macro parses a string and returns the parsed term.
///
/// # Panics
///
/// A panic is caused if the string cannot be parsed.
#[macro_export]
macro_rules! parse_term {
    ($str:literal) => {
        fun::parser::fun::TermParser::new()
            .parse($str)
            .unwrap_or_else(|_| panic!("Could not parse input: {}", $str))
    };
}

#[cfg(test)]
mod parser_tests {
    use std::rc::Rc;

    use super::*;
    use crate::{
        syntax::{
            Codata, CtorSig, Data, DtorSig, TypeArgs, TypeContext, context::TypingContext, program::Program, terms::{Lit, Paren, Term, XVar}, types::Ty, util::dummy_span,
        }, test_common::def_mult,
    };

    #[test]
    fn parse_parens() {
        let parser = fun::TermParser::new();
        let expected = Paren {
            span: dummy_span(),
            inner: Rc::new(Term::Lit(Lit::mk(22))),
        }
        .into();
        assert_eq!(parser.parse("(22)"), Ok(expected));
    }

    #[test]
    fn parse_lit() {
        let parser = fun::TermParser::new();
        let expected = Term::Lit(Lit::mk(22));
        assert_eq!(parser.parse("22"), Ok(expected));
    }

    #[test]
    fn parse_var() {
        let parser = fun::TermParser::new();
        let expected = XVar::mk("x").into();
        assert_eq!(parser.parse("x"), Ok(expected));
    }

    #[test]
    fn parse_int() {
        let parser = fun::TyParser::new();
        let expected = Ty::mk_i64();
        assert_eq!(parser.parse("i64"), Ok(expected));
    }

    #[test]
    fn parse_ctx() {
        let mut ctx = TypingContext::default();
        ctx.add_var("x", Ty::mk_i64());
        ctx.add_covar("a", Ty::mk_i64());
        let parser = fun::OptContextParser::new();
        assert_eq!(parser.parse("(x : i64, a:cns i64)"), Ok(ctx))
    }

    /// the parser still produces the old style of Type Vars: Type Declaration with no argument.
    /// They are converted later in the type checking. To enable testing of the parser this function is nice to have.
    fn make_old_type_var(name: &str) -> Ty {
        Ty::mk_decl(name, TypeArgs::default())
    }

    #[test]
    fn parse_prog() {
        let parser = fun::ProgParser::new();
        let mut ctx_cons = TypingContext::default();
        ctx_cons.add_var("x", make_old_type_var("A"));
        ctx_cons.add_var(
            "xs",
            Ty::mk_decl(
                "List",
                TypeArgs::mk(vec![make_old_type_var("A")]),
            ),
        );
        let data_list = Data {
            span: None,
            name: "List".to_owned(),
            type_params: TypeContext::mk(&vec!["A"]),
            ctors: vec![
                CtorSig {
                    span: None,
                    name: "Nil".to_owned(),
                    args: TypingContext::default(),
                },
                CtorSig {
                    span: None,
                    name: "Cons".to_owned(),
                    args: ctx_cons,
                },
            ],
        };

        let codata_stream = Codata {
            span: None,
            name: "Stream".to_owned(),
            type_params: TypeContext::mk(&vec!["A"]),
            dtors: vec![
                DtorSig {
                    span: None,
                    name: "head".to_owned(),
                    args: TypingContext::default(),
                    cont_ty: make_old_type_var("A"),
                },
                DtorSig {
                    span: None,
                    name: "tail".to_owned(),
                    args: TypingContext::default(),
                    cont_ty: Ty::mk_decl(
                        "Stream",
                        TypeArgs::mk(vec![make_old_type_var("A")]),
                    ),
                },
            ],
        };

        let expected = Program {
            declarations: vec![
                data_list.into(),
                codata_stream.into(),
                def_mult().into(),
            ],
        };
        let result = parser.parse(
            "data List[A] { Nil, Cons(x:A,xs:List[A]) }
            codata Stream[A] { head : A , tail : Stream[A] }
            def mult(l:List[i64]):i64 { l.case[i64] {Nil => 1, Cons(x, xs) => x*mult(xs)} }",
        );
        assert_eq!(result, Ok(expected))
    }
}
