[source.crates-io]
replace-with="vendored-sources"

[source."git+https://github.com/polarity-lang/codespan.git?rev=542320ab177fd38fff3a398a97b3f0352e065149"]
git = "https://github.com/polarity-lang/codespan.git"
rev = "542320ab177fd38fff3a398a97b3f0352e065149"
replace-with = "vendored-sources"

[source.vendored-sources]
directory="vendor"

