name: x86_64 Tests 

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  statuses: write

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Examples
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: uraimo/run-on-arch-action@v2         
        name: Run commands         
        id: runcmd         
        with:           
        arch: x86_64
        distro: ubuntu22.04
        run: cargo run -p endtoend 
